/**
 * Auto-generated by scripts/extract-status-badge.py
 * Source: pret/pokeheartgold src/battle/battle_hp_bar_data.h tiles 0x29..0x37
 * Palette: files/a/0/0/8 NARC member 71 (0x47).
 * 5 battle status chips — pixel data is the same chip silhouette per status,
 * only the colour pair differs (chip body + 3-letter glyph).
 */

export type StatusKind = "par" | "frz" | "slp" | "psn" | "brn";

export type StatusEntry = {
  /** native pixel width */
  w: number;
  /** native pixel height */
  h: number;
  /** colours — palette[0] of the source NCLR is omitted (NDS transparent) */
  palette: readonly string[];
  /** [x, y, w, h, paletteIndex+1]; chip silhouette only — the 3-letter glyph is NOT here */
  rects: ReadonlyArray<readonly [number, number, number, number, number]>;
  /** suggested colour for the overlaid label text (the in-game glyph colour) */
  glyph: string;
  /** body fill colour, if you want to colour-key extras to this chip */
  body: string;
};

export const STATUS_CHIPS: Record<StatusKind, StatusEntry> = {
  par: {
    w: 24, h: 8,
    palette: ["#B8B8B8", "#F8B000", "#E0E0E0"],
    rects: [[0,0,2,1,3],[2,0,20,8,2],[22,0,2,1,3],[0,1,1,1,1],[1,1,1,6,2],[22,1,1,6,2],[23,1,1,1,1],[0,2,1,1,3],[23,2,1,1,3],[0,3,1,5,1],[23,3,1,5,1],[1,7,1,1,1],[22,7,1,1,1]],
    glyph: "#B06808",
    body: "#F8B000",
  },
  frz: {
    w: 24, h: 8,
    palette: ["#B8B8B8", "#4890F8", "#E0E0E0"],
    rects: [[0,0,2,1,3],[2,0,20,8,2],[22,0,2,1,3],[0,1,1,1,1],[1,1,1,6,2],[22,1,1,6,2],[23,1,1,1,1],[0,2,1,1,3],[23,2,1,1,3],[0,3,1,5,1],[23,3,1,5,1],[1,7,1,1,1],[22,7,1,1,1]],
    glyph: "#3060D8",
    body: "#4890F8",
  },
  slp: {
    w: 24, h: 8,
    palette: ["#B8B8B8", "#F8F8F8", "#E0E0E0"],
    rects: [[0,0,2,1,3],[2,0,20,8,2],[22,0,2,1,3],[0,1,1,1,1],[1,1,1,6,2],[22,1,1,6,2],[23,1,1,1,1],[0,2,1,1,3],[23,2,1,1,3],[0,3,1,5,1],[23,3,1,5,1],[1,7,1,1,1],[22,7,1,1,1]],
    glyph: "#707070",
    body: "#F8F8F8",
  },
  psn: {
    w: 24, h: 8,
    palette: ["#B8B8B8", "#D858D0", "#E0E0E0"],
    rects: [[0,0,2,1,3],[2,0,20,8,2],[22,0,2,1,3],[0,1,1,1,1],[1,1,1,6,2],[22,1,1,6,2],[23,1,1,1,1],[0,2,1,1,3],[23,2,1,1,3],[0,3,1,5,1],[23,3,1,5,1],[1,7,1,1,1],[22,7,1,1,1]],
    glyph: "#A83038",
    body: "#D858D0",
  },
  brn: {
    w: 24, h: 8,
    palette: ["#B8B8B8", "#F85828", "#E0E0E0"],
    rects: [[0,0,2,1,3],[2,0,20,8,2],[22,0,2,1,3],[0,1,1,1,1],[1,1,1,6,2],[22,1,1,6,2],[23,1,1,1,1],[0,2,1,1,3],[23,2,1,1,3],[0,3,1,5,1],[23,3,1,5,1],[1,7,1,1,1],[22,7,1,1,1]],
    glyph: "#A83038",
    body: "#F85828",
  },
};
